### ISSUE TITLE
AXISn_FAULT is defined in capitals in Config.Ramps14.h, while mentioned as Axisn_FAULT in OnStep.ino

### ISSUE THREAD

**Issue by salehram** [hjd1964/OnStep#102]
Hello,

I was just compiling the latest beta release of OnStep and I ran into an issue about a typo related to AXIS**n**_FAULT.

While it is defined in Config.Ramps14.h in capital case, in OnStep there are mentions for it in first letter as capital only (Axis**n**_FAULT), which resulted in failure to compile.

I was manually able to fix it by correcting the case of the letters however I am not sure if this is the case for the other config files or this is a specific for Config.Ramps14.h only.

The definition in Config.Ramps14.h is at line 183 and 184
The wrong instances in OnStep.ino are in lines:
361
364
372
375

Just thought I leave this for your kind information and check!
Regards

**Comment by hjd1964** [comment]
You are confusing the config option with the pin definition.  The pin definition in this case is not supported and not present, hence the compile error.

This is clear per the comments in the Config.Ramps14.h file.
