### ISSUE TITLE
SHC: Add object names for Messier and Caldwell

### ISSUE THREAD

**Issue by kbahey** [hjd1964/OnStep#118]
Would be nice to have the object name for Messier and Caldwell. Storage on the Teensy 3.2 should be able to accomodate 109 x 2 x 12 bytes of extra storage.

**Comment by hjd1964** [comment]
The T3.2 has about 60,000 bytes free (using the "faster" default compile) so that's no problem.
For a "smallest" compile, about 82,000 bytes free.

**Comment by hjd1964** [comment]
Completed.
