### ISSUE TITLE
Cunfiguration for Arduino Nano Atmega328p

### ISSUE THREAD

**Issue by andregcoimbra** [hjd1964/OnStep#129]
Hi,

I have a Arduino Nano Atmega328p and driver A4988 already configured for 1/16 resolution. Is possible create the configuration file to use them?

Best regards.

**Comment by hjd1964** [comment]
No way, not even close.

**Comment by hjd1964** [comment]
OnStep will run on many platforms.
Teensy3.2,3.5,3.6 STM32 ESP32... and the Mega2560
The MKS Gen-L 3D printer board is my personal favorite for cheap and easy.  
Fully supported in OnStep.
