### ISSUE TITLE
SHC - star selection during align

### ISSUE THREAD

**Issue by peterdulowsky** [hjd1964/OnStep#132]
When you do align, select the star, goto it, and then you realize it is behind an obstacle (roof or tree in my case) there is no way how to select another star or cancel alignment. You can cancel alignment when the scope is still slewing but not when the goto has finished. Can this be modified? Perhaps, long press of Shift button to re-enter star selection dialogue?

**Comment by hjd1964** [comment]
This feature has been added to the SHC, so I'm closing this issue.
