### ISSUE TITLE
Spreadsheet problem

### ISSUE THREAD

**Issue by RecifeStargazer** [hjd1964/OnStep#14]
Hi 

I've made a onStep mega based, and after testing, it's like the spreadsheet is giving a doubled value on 
StepsPerDegree and StepsPerWormRotation. I've checked the m0,m1 and m2 voltages and it seems to be ok. Weird...

**Comment by hjd1964** [comment]
I suggest you look elsewhere, the spreadsheet has been used by hundreds of users without issue.  Make sure the gear ratios are correct.  Make sure the stepper motor steps/rotation is correct.  Make sure the micro-step mode is programmed correctly AND the AXISn_STEP_GOTO values are correct.  Feel free to email me **with more info** so I can examine the issue in detail.  My address is in OnStep.ino
