### ISSUE TITLE
Repeatability of alignment results

### ISSUE THREAD

**Issue by kbahey** [hjd1964/OnStep#143]
For the last two nights, I did a 6 star align, without touching the alt and az knobs, but got very different results.

All alignment was done via plate solving. 

For Aug 24th, I did a Refine PA, and then a 6 star align, the results were:

► 21"   ▲ 208" 
The raw values from INDI were: Alt +208 Az -16

On Aug 25th, I did not move the mount at all, nor touch the knobs.

A 6 star align got the results:

◄ 175"   ▼ 208"
Raw values from INDI: Alt -208" Az 128"

Note the very different values.

Why should that be? An error of 32" one way or the other is fine, but for +208 to be -208? How can that be?

I am using a patch to increase granularity. This makes the code for the STM32 just like Teensy by removing the FAST_PROCESSOR defines in AlignEq.ino. But that should not matter.

**Comment by kbahey** [comment]
Another example of this happening

Two nights ago, I did a 3 star align, followed by a Refine PA, then another 3 Star align. 

The results were:
► 21"   ▼ 80" 

Then, left the scope outside, covered it.

The next night, did a 3 star align, and the results were:
◄ 0'   ▼ 5' 

Why is there such a discrepancy, despite the mount being in the exact same position, and not moved at all?

**Comment by hjd1964** [comment]
I don't know, let me know when you figure it out.
