### ISSUE TITLE
Negative array index in command parser

### ISSUE THREAD

**Issue by bgilsrud** [hjd1964/OnStep#15]
I think there is an unintentional negative array index used in the Command.h:ready() function:

```
    bool ready() {
      if ((cb[cbp-1]=='#') && (cbp==1)) flush();
      return (cb[cbp-1]=='#');
    }
```
If cbp=0, which I think it would be on the receipt of the first character of a command then memory outside of the cb array would be accessed. I think the following should work around this (untested):

```
    bool ready() {
      if (!cbp) return false;
      if ((cb[cbp-1]=='#') && (cbp==1)) flush();
      return (cb[cbp-1]=='#');
    }
```

**Comment by hjd1964** [comment]
Thanks, good catch.
This applies to my OCS also. Fix seems to work fine and is low risk so I updated.
