### ISSUE TITLE
Add MCU and Pinmap to verbose debug output

### ISSUE THREAD

**Issue by kbahey** [hjd1964/OnStep#164]
Right now, the output does not say what either the MCU architecture or the pinmap is.

It would be informative if they did.

To do so, we need to add something like this to each HAL file:

```
#define MCU "STM32F1"
#define MCU "Teensy 3.5"
#define MCU "ESP32"
```
And in each pinmap file, there would be:

```
#define PINMAP_DESC "Blue Pill PCB"
#define PINMAP_DESC "MaxPCB v2"
#define PINMAP_DESC "W32+CNCv3"
```

Then it is a matter of printing the above strings ...

**Comment by hjd1964** [comment]
Code was added to do this.
