### ISSUE TITLE
Mega2560Alt or AltMega2560

### ISSUE THREAD

**Issue by pebdev** [hjd1964/OnStep#185]
Hi,

Currently I add support of a custom board and I found this. I think it's a mistake :

In the file **Constants.h** :
```
#define AltMega2560                  3 // Obsolete
```

In the file **src/pinmaps/Models.h** :
```
#if PINMAP == Mega2560Alt
  #define PINMAP_STR "Alternate"
  #include "Pins.Mega2560Alt.h"
#endif
```

I can't find usage of **AltMega2560** and I can't find definition of **Mega2560Alt**.
Names are not aligned, is it normal ?

I work on the **release-4.24**.

Note : I take the opportunity to thank you for this amazing job ! 🥇

**Comment by tsatatwer** [comment]
Hi ,

I am working with mega2560 I edited the Config.h and added this :
`#define PINMAP AltMega2560`

Then I get many new errors ?????
