### ISSUE TITLE
Validate.h:380:4: error: #error "Configuration (Config.h): You must specify a PINMAP!"    #error "Configuration (Config.h): You must specify a PINMAP!"

### ISSUE THREAD

**Issue by tsatatwer** [hjd1964/OnStep#188]
Hi ,

while compiling I get this error:

**Validate.h:380:4: error: #error "Configuration (Config.h): You must specify a PINMAP!"
   #error "Configuration (Config.h): You must specify a PINMAP!**
   
   Any idea. Thanks

**Comment by CyberianIce** [comment]
You must edit Config.h file according to your hardware. Error suggests you did not select PINMAP at all.

**Comment by tsatatwer** [comment]
I did :

#define PINMAP                       AltMega2560 

Then I get many new errors ?????

**Comment by CyberianIce** [comment]
For Arduino Mega 2560, You can use #define PINMAP Ramps14 and you can have all features on that board (no matter if you use ramps shield or not). And please join [OnStep group](https://onstep.groups.io/) to get community support, this is not proper place for that.

**Comment by tsatatwer** [comment]
@CyberianIce many thanks indeed...already joined the OnStep group I appreciated the great support and very productive project .
I will close this issue
