### ISSUE TITLE
typo in guide.ino GR_PLUSEGUIDE instead of GR_PULSEGUIDE

### ISSUE THREAD

**Issue by magore** [hjd1964/OnStep#192]
OnStep/Guide.ino: In function 'void ST4()':
Guide:568:41: error: 'GR_PLUSEGUIDE' was not declared in this scope; did you mean 'GR_PULSEGUIDE'?
  568 |             startGuideAxis1(newDirAxis1,GR_PLUSEGUIDE,GUIDE_TIME_LIMIT*1000,false);
      |                                         ^~~~~~~~~~~~~
      |                                         GR_PULSEGUIDE

**Comment by hjd1964** [comment]
The master branch is not maintained nor is it recommended for use.

Use release-4.24 or OnStepX if you want something more cutting edge.
