### ISSUE TITLE
Trojan:Script/Wacatac.B!ml (Trojan detected in OnStep 4.24 )

### ISSUE THREAD

**Issue by galvbass** [hjd1964/OnStep#193]
I just downloaded the last version of the OnStep and my windows Defender blocked a trojan in OnStep files: 
*OnStep-release-4.24 (2).zip->OnStep-release-4.24/addons/WiFi/Globals.h
*OnStep-release-4.24 (2).zip->OnStep-release-4.24/addons/Ethernet/Globals.h
*webfile:OnStep-release-4.24 (2).zip|https://codeload.github.com/hjd1964/OnStep/zip/refs/heads/release-4.24|pid:496,ProcessStart:133151572927477066
Please take action on this!

**Comment by vzr314** [comment]
Perhaps the file is contaminated on your side. Please check your OS, browser or SSL proxy.

**Comment by hjd1964** [comment]
False positive or as Cyberianice said is my interpretation, I see no other possibility.

**Comment by galvbass** [comment]
Thank you so much guys, everything is good was false positive.Thanks for all your support.Best regards.

Sent from Yahoo Mail on Android 
 
  On Sun, Dec 11, 2022 at 5:37 AM, Howard ***@***.***> wrote:   


False positive or as Cyberianice said is my interpretation, I see no other possibility.
