### ISSUE TITLE
In release-4.24, I used Visual Studio+micro (an Arduino extension) encountered a compilation error.

### ISSUE THREAD

**Issue by LHF-CN** [hjd1964/OnStep#196]
Astro.ino:
`double trueRefrac(double Alt, double Pressure=1010.0, double Temperature=10.0)`
`double apparentRefrac(double Alt, double Pressure=1010.0, double Temperature=10.0)`

`Alt = Alt+trueRefrac(Alt,)/60.0;`
`Alt = Alt-apparentRefrac(Alt)/60.0;`
`double Alt1_ = Alt1 - ( trueRefrac(Alt1) / 60.0 );`
`double Alt2_ = Alt2 - ( trueRefrac(Alt2) / 60.0 );`

These two functions are built, but an error occurs and the compiler prompts for the wrong default and number of arguments, respectively:
373:78: error: default argument given for parameter 3 of 'double trueRefrac(double, double, double)' [-fpermissive]
413:27: error: too few arguments to function 'double trueRefrac(double, double, double)

If I change the code a little, it builds fine:
`double trueRefrac(double Alt, double Pressure, double Temperature)`
`double apparentRefrac(double Alt, double Pressure, double Temperature)`

`Alt = Alt+trueRefrac(Alt, 1010.0, 10.0)/60.0;`
`Alt = Alt-apparentRefrac(Alt, 1010.0, 10.0)/60.0;`
`double Alt1_ = Alt1 - ( trueRefrac(Alt1, 1010.0, 10.0) / 60.0 );`
`double Alt2_ = Alt2 - ( trueRefrac(Alt2, 1010.0, 10.0) / 60.0 );`

Can I do that?

**Comment by hjd1964** [comment]
Not supported
