### ISSUE TITLE
Focuser2 enabled without Focuser1 being enabled

### ISSUE THREAD

**Issue by kbahey** [hjd1964/OnStep#22]
Trying to compile OnStep Alpha gives the error : Focuser2 enabled without Focuser1 being enabled. 

This is traced to Config.Ramps14.h having :

#define FOCUSER2_ON 

But earlier FOCUSER1_OFF

Changing to FOCUER2_OFF solves this.

**Comment by hjd1964** [comment]
More config files == more things to go wrong, thanks.
