### ISSUE TITLE
Undeclared define in Initialize.ino?

### ISSUE THREAD

**Issue by kbahey** [hjd1964/OnStep#28]
In Initialize.ino, line 342, there is this:

`#if !defined(RememberMaxRate_ON) && !defined(REMEMBER_MAX_RATE_ON)
`
The RememberMaxRate_ON seems to be an error, since it is not defined anywhere.

Also, isn't this code reversed? Shouldn't it be without the '!', like so:

```
#if defined(defined(REMEMBER_MAX_RATE_ON)
//... EEPROM write
#endif 
```

**Comment by hjd1964** [comment]
RememberMaxRate_ON is for backwards compatibility and can be phased out at some point.  Probably getting to that point.

Lol, probably should have named the #define "REMEMBER_MAXRATE_ON" but whatever!

The conditional logic is as intended.
